### PR TITLE
add uint vs int promotion tables to numeric input types

### PR DESCRIPTION
**Pull request by pmeier**

### CODE REVIEW

**Comment by asmeurer** [comment]
Does this add anything that was not already there?

**Comment by pmeier** [comment]
Yes, the mixed `uint` vs. `int` promotion tables. They are currently not covered by `"numeric"` input types, but numeric should be everything except bool, no?

**Comment by asmeurer** [comment]
This is just extracting the values of those dictionaries, which should already include everything. Maybe this should be done in a less inconspicuous way.

**Comment by pmeier** [comment]
:facepalm: Sorry, my bad.

**Pull request closed without merging**
