### PR TITLE
`test_take`

### PR DESCRIPTION
**Pull request by honno**
Somewhat comprehensive `test_take`

### CODE REVIEW

**Comment by asmeurer** [comment]
Have you tried this on different libraries? I know pytorch is missing the `axis` argument, but numpy, cupy, numpy.array_api (git), and cupy.array_api (git) all have take that should be fully compliant.

**Comment by honno** [comment]
> Have you tried this on different libraries? I know pytorch is missing the `axis` argument, but numpy, cupy, numpy.array_api (git), and cupy.array_api (git) all have take that should be fully compliant.

I should of mentioned I really just developed this test for top-level `numpy`. Just tried this on `cupy`, `array_api_compat.numpy` and `array_api_compat.cupy`, which all pass this test in its current iteration.

**Comment by asmeurer** [comment]
Yeah I didn't either, though maybe we should try to nudge people to the compat library. 

If this works with those libraries I'm +1 to merge.

**Comment by honno** [comment]
The `.array_api` namespaces are kinda weird to test with as they don't implement complex dtypes, so I'll ignore 'em for now and get this merged given it works with NumPy-proper.

**Pull request merged**
