### PR TITLE
helpers: avoid mutation in invertible_matrices

### PR DESCRIPTION
**Pull request by jakevdp**
Part of the fix for #188

### CODE REVIEW

**Comment by asmeurer** [comment]
This looks fine. Generally I wouldn't want to make use of so many array functions in a strategy, but for the linalg strategies it's unavoidable and really not a problem to assume everything else works there.

**Comment by jakevdp** [comment]
CI errors are due to using an old version of NumPy; hopefully #202 will fix it.

**Comment by jakevdp** [comment]
Let me know if there's anything to be done here – the mutation in the test infrastructure here and elsewhere necessetates us skipping this test in JAX, so we don't have any test coverage for the associated linear algebra APIs.

**Comment by kgryte** [comment]
@honno @asmeurer Is there anything blocking getting this merged?

**Comment by honno** [comment]
LGTM thanks.

**Review by honno — APPROVED** [review]
LGTM thanks.

**Pull request merged**
